//CareerConstant
export const CAREER_LIST_REQUEST ='CARRIER_LIST_REQUEST'
export const CAREER_LIST_SUCCESS ='CARRIER_LIST_SUCCESS'
export const CAREER_LIST_FAIL ='CARRIER_LIST_FAIL' 


export const CAREER_DETAILS_REQUEST ='CARRIER_DETAILS_REQUEST'
export const CAREER_DETAILS_SUCCESS ='CARRIER_DETAILS_SUCCESS'
export const CAREER_DETAILS_FAIL ='CARRIER_DETAILS_FAIL' 